apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fluentd.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentd.name }}
stringData:
  {{- if .Values.fluentd.azure.logAnalytics.enabled }}
  sharedKey: {{ .Values.fluentd.azure.logAnalytics.sharedKey | quote }}
  workspaceID: {{ .Values.fluentd.azure.logAnalytics.workspaceId | quote }}
  {{- end}} 
  {{- if and .Values.fluentd.elasticsearch.enabled .Values.fluentd.elasticsearch.secured}}
  elasticsearchUser: {{ .Values.fluentd.elasticsearch.user | quote }}
  elasticsearchPassword: {{ .Values.fluentd.elasticsearch.password | quote }}
  {{- end}} 
  