apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentd.name }}
  annotations:
    {{- if .Values.giantswarm.monitoring.enabled }}
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-path: "api/v1/metrics/prometheus"
    giantswarm.io/monitoring-port: "24224"
    {{- end }}
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/v1/metrics/prometheus"
spec:
  ports:
    - name: fluentd
      port: 24224
      targetPort: 24224
  selector:
    app: {{ .Values.fluentd.name }}
