version: 2.1
orbs:
  architect: giantswarm/architect@2.1.0

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push chart to app catalog"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "fluent-logshipping-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
