apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentbit.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentbit.name }}
  annotations:
    {{- if .Values.giantswarm.monitoring.enabled }}
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-path: "api/v1/metrics/prometheus"
    giantswarm.io/monitoring-port: "2020"
    {{- end }}
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/v1/metrics/prometheus"
spec:
  ports:
    - name: fluentbit
      port: 2020
      targetPort: 2020
  selector:
    app: {{ .Values.fluentbit.name }}
