kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.fluentbit.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.fluentbit.name }}
  ingress:
  - ports:
    - port: {{ .Values.fluentbit.port }}
      protocol: {{ .Values.fluentbit.protocol }}
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
  policyTypes:
  - Egress
  - Ingress
