apiVersion: v1
kind: Service
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    app: fluentbit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/v1/metrics/prometheus"
spec:
  ports:
    - name: fluentbit
      port: 2020
      targetPort: 2020
  selector:
    app: fluentbit
