apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.fluentd.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/v1/metrics/prometheus"
spec:
  ports:
    - name: fluentd
      port: 24224
      targetPort: 24224
  selector:
    app: {{ .Values.fluentd.name }}
