apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentbit.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentbit.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fluentbit.name }}
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: {{ .Values.fluentbit.name }}
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: {{ .Values.fluentbit.name }}
      securityContext:
        runAsUser: {{ .Values.fluentbit.userID }}
        runAsGroup: {{ .Values.fluentbit.groupID }}
      containers:
      - name: {{ .Values.fluentbit.name }}
        image: {{ .Values.image.registry }}/{{ .Values.fluentbit.image.name }}:{{ .Values.fluentbit.image.tag }}
        env:
        - name: FLUENTD_HOST
          value: "{{ .Values.fluentd.name }}.{{ .Release.Namespace }}.svc"
        - name: FLUENTD_PORT
          value: "{{ .Values.fluentd.port }}"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: {{ .Values.fluentbit.port }}
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.fluentbit.port }}
          initialDelaySeconds: 10
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: {{ .Values.fluentbit.name }}-config
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
